### ISSUE TITLE
Error when using ESM CDNs - `The requested module does not provide an export named 'toLatLngBounds'`

### ISSUE THREAD

**Issue by gavinr-maps** [Esri/esri-leaflet#1386]
### Describe the bug

When trying to load Esri Leaflet via ES Modules via an ESM CDN like [esm.sh](https://esm.sh/) or [esm.run by jsDelivr](https://www.jsdelivr.com/esm), there is an error:

> Uncaught SyntaxError: The requested module .... does not provide an export named 'toLatLngBounds' ...

#### Notes:
- This is possibly related or a duplicate of #1343 
- This is similar or the same as what was discussed [here](https://github.com/Esri/esri-leaflet/issues/1342#issuecomment-1258992755).
- This was recently re-reported by @mbostock [here](https://github.com/Esri/esri-leaflet/pull/1343#issuecomment-1906806585).
- This is also tangentially related to #1338

#### esm.run reproduction:

1. Open https://jsbin.com/xokuzam/1/edit?html,output
2. View the developer console
    - Expected: the map loads and no errors
    - Actual:
        > Uncaught SyntaxError: The requested module '/npm/leaflet@1.9.4/+esm' does not provide an export named 'toLatLngBounds' (at +esm:7:265)

### System Info

```shell
- Leaflet v1.9.4
- Esri Leaflet v3.0.12
```

### Additional Information

It does look like Leaflet exports as `latLngBounds` - https://github.com/Leaflet/Leaflet/blob/b2fd591c33785227e0d4036c1a80a00bd2debd53/src/geo/index.js#L2

... so is the fix as simple as changing this:
https://github.com/Esri/esri-leaflet/blob/48cfd690614594428b09da284e30e08892a8ab6e/src/Layers/FeatureLayer/FeatureGrid.js#L3

to:

```js
latLngBounds,
```

?

**Comment by gavinr-maps** [comment]
I have published a separate version of Esri Leaflet that includes the changing  

https://github.com/Esri/esri-leaflet/blob/48cfd690614594428b09da284e30e08892a8ab6e/src/Layers/FeatureLayer/FeatureGrid.js#L3

to:

```js
latLngBounds,
```

**Comment by Kizito007** [comment]
Hey @gavinr-maps 

Does this issue still persist? If so could you please guide me through it, I'd love to give a hand but I'm kinda lost through the threads.

Thanks

**Comment by hhkaos** [comment]
Hi @Kizito007 I just followed the reproduction steps above and I still see the error showing (on the [current version 3.0.12](https://developers.arcgis.com/esri-leaflet/)):
![2024-10-24_15-24-42](https://github.com/user-attachments/assets/3092982d-4225-4c43-b684-6700068220dc)

**Comment by gavinr-maps** [comment]
Turns out the fix that I mentioned in https://github.com/Esri/esri-leaflet/issues/1386#issuecomment-2176237660 is the solution. But the follow-on issue is an issue with the CDN esm.run. If you switch it to use Cloudflare's esm.sh service, it works:
https://jsbin.com/rahage/7/edit?html,output

I will be issuing a PR shortly for that small change. No additional work needed on this issue.

**Comment by gavinr-maps** [comment]
Example of using Esri Leaflet with esm.sh CDN: https://jsbin.com/bapubuj/1/edit?html,output
